version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_auth
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:latest
    container_name: redis_auth
    ports:
      - 6379:6379
    volumes:
      - redis_auth_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  postgres_auth_data:
  redis_auth_data:
